---
- name: Setup Apache webserver 
  hosts: webserver 
  gather_facts: False
  become: yes

  vars_files:
    - vars/main.yml 
   
  pre_tasks:
    ## ubuntu 18, install python
    - include: pre-task.yml
       
  roles:
    - { roles: geerlingguy.apache } 
    - { roles: geerlingguy.php} 

    

